# Generated by Django 5.1.7 on 2025-03-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_configuracaoia_interacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoia",
            name="provedor",
            field=models.CharField(
                choices=[("deepseek", "DeepSeek"), ("openai", "OpenAI")],
                default="deepseek",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoia",
            name="modelo",
            field=models.CharField(
                choices=[
                    ("deepseek-chat", "DeepSeek Chat"),
                    ("deepseek-lite", "DeepSeek Lite"),
                    ("deepseek-v2", "DeepSeek V2"),
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                ],
                default="deepseek-chat",
                max_length=50,
            ),
        ),
    ]
